"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2023 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import substrait.type_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class EntryPoint(google.protobuf.message.Message):
    """Record the current storage metadata path in a static local file.
    A mutation to storage generates a new metadata file. The current metadata
    file path is either persisted in the entry point file, or an external
    catalog (not implemented yet).
    NEXT_ID: 2
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METADATA_FILE_FIELD_NUMBER: builtins.int
    metadata_file: builtins.str
    """File path of the current storage metadata file."""
    def __init__(
        self,
        *,
        metadata_file: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["metadata_file", b"metadata_file"]) -> None: ...

global___EntryPoint = EntryPoint

@typing_extensions.final
class StorageMetadata(google.protobuf.message.Message):
    """Metadata persisting the current status of a storage, including logical
    metadata such as schema, and physical metadata persisted as a history of
    snapshots
    NEXT_ID: 7
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StorageMetadata._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TYPE_UNSPECIFIED: StorageMetadata._Type.ValueType  # 0
        DATASET: StorageMetadata._Type.ValueType  # 1
        """The dataset type supports fully managed storage features."""

    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        """The storage type."""

    TYPE_UNSPECIFIED: StorageMetadata.Type.ValueType  # 0
    DATASET: StorageMetadata.Type.ValueType  # 1
    """The dataset type supports fully managed storage features."""

    @typing_extensions.final
    class SnapshotsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___Snapshot: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___Snapshot | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    CREATE_TIME_FIELD_NUMBER: builtins.int
    LAST_UPDATE_TIME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    SCHEMA_FIELD_NUMBER: builtins.int
    CURRENT_SNAPSHOT_ID_FIELD_NUMBER: builtins.int
    SNAPSHOTS_FIELD_NUMBER: builtins.int
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Create time of the storage."""
    @property
    def last_update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Last update time of the storage."""
    type: global___StorageMetadata.Type.ValueType
    @property
    def schema(self) -> global___Schema:
        """The storage schema."""
    current_snapshot_id: builtins.int
    """The current snapshot ID."""
    @property
    def snapshots(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___Snapshot]:
        """All alive snapshots with snapshot ID as key."""
    def __init__(
        self,
        *,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        last_update_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        type: global___StorageMetadata.Type.ValueType = ...,
        schema: global___Schema | None = ...,
        current_snapshot_id: builtins.int = ...,
        snapshots: collections.abc.Mapping[builtins.int, global___Snapshot] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time", b"create_time", "last_update_time", b"last_update_time", "schema", b"schema"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["create_time", b"create_time", "current_snapshot_id", b"current_snapshot_id", "last_update_time", b"last_update_time", "schema", b"schema", "snapshots", b"snapshots", "type", b"type"]) -> None: ...

global___StorageMetadata = StorageMetadata

@typing_extensions.final
class Schema(google.protobuf.message.Message):
    """The storage logical schema where user provided types are persisted instead
    of their physical storage format.
    NEXT_ID: 2
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIELDS_FIELD_NUMBER: builtins.int
    @property
    def fields(self) -> substrait.type_pb2.NamedStruct:
        """Fields persisted as Substrait named struct."""
    def __init__(
        self,
        *,
        fields: substrait.type_pb2.NamedStruct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["fields", b"fields"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["fields", b"fields"]) -> None: ...

global___Schema = Schema

@typing_extensions.final
class Snapshot(google.protobuf.message.Message):
    """Storage snapshot persisting physical metadata such as manifest file paths.
    It is used for obtaining all alive data file paths for a given snapshot.
    NEXT_ID: 3
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SNAPSHOT_ID_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    snapshot_id: builtins.int
    """The snapshot ID."""
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The create time of the snapshot."""
    def __init__(
        self,
        *,
        snapshot_id: builtins.int = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time", b"create_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["create_time", b"create_time", "snapshot_id", b"snapshot_id"]) -> None: ...

global___Snapshot = Snapshot
