# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: substrait/capabilities.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csubstrait/capabilities.proto\x12\tsubstrait\"\xfb\x01\n\x0c\x43\x61pabilities\x12\x1a\n\x12substrait_versions\x18\x01 \x03(\t\x12$\n\x1c\x61\x64vanced_extension_type_urls\x18\x02 \x03(\t\x12\x42\n\x11simple_extensions\x18\x03 \x03(\x0b\x32\'.substrait.Capabilities.SimpleExtension\x1a\x65\n\x0fSimpleExtension\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x15\n\rfunction_keys\x18\x02 \x03(\t\x12\x11\n\ttype_keys\x18\x03 \x03(\t\x12\x1b\n\x13type_variation_keys\x18\x04 \x03(\tBW\n\x12io.substrait.protoP\x01Z*github.com/substrait-io/substrait-go/proto\xaa\x02\x12Substrait.Protobufb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'substrait.capabilities_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022io.substrait.protoP\001Z*github.com/substrait-io/substrait-go/proto\252\002\022Substrait.Protobuf'
  _CAPABILITIES._serialized_start=44
  _CAPABILITIES._serialized_end=295
  _CAPABILITIES_SIMPLEEXTENSION._serialized_start=194
  _CAPABILITIES_SIMPLEEXTENSION._serialized_end=295
# @@protoc_insertion_point(module_scope)
