# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: substrait/plan.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from substrait import algebra_pb2 as substrait_dot_algebra__pb2
from substrait.extensions import extensions_pb2 as substrait_dot_extensions_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14substrait/plan.proto\x12\tsubstrait\x1a\x17substrait/algebra.proto\x1a%substrait/extensions/extensions.proto\"X\n\x07PlanRel\x12\x1d\n\x03rel\x18\x01 \x01(\x0b\x32\x0e.substrait.RelH\x00\x12\"\n\x04root\x18\x02 \x01(\x0b\x32\x12.substrait.RelRootH\x00\x42\n\n\x08rel_type\"\xbc\x02\n\x04Plan\x12#\n\x07version\x18\x06 \x01(\x0b\x32\x12.substrait.Version\x12@\n\x0e\x65xtension_uris\x18\x01 \x03(\x0b\x32(.substrait.extensions.SimpleExtensionURI\x12\x44\n\nextensions\x18\x02 \x03(\x0b\x32\x30.substrait.extensions.SimpleExtensionDeclaration\x12%\n\trelations\x18\x03 \x03(\x0b\x32\x12.substrait.PlanRel\x12\x44\n\x13\x61\x64vanced_extensions\x18\x04 \x01(\x0b\x32\'.substrait.extensions.AdvancedExtension\x12\x1a\n\x12\x65xpected_type_urls\x18\x05 \x03(\t\"2\n\x0bPlanVersion\x12#\n\x07version\x18\x06 \x01(\x0b\x32\x12.substrait.Version\"o\n\x07Version\x12\x14\n\x0cmajor_number\x18\x01 \x01(\r\x12\x14\n\x0cminor_number\x18\x02 \x01(\r\x12\x14\n\x0cpatch_number\x18\x03 \x01(\r\x12\x10\n\x08git_hash\x18\x04 \x01(\t\x12\x10\n\x08producer\x18\x05 \x01(\tBW\n\x12io.substrait.protoP\x01Z*github.com/substrait-io/substrait-go/proto\xaa\x02\x12Substrait.Protobufb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'substrait.plan_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022io.substrait.protoP\001Z*github.com/substrait-io/substrait-go/proto\252\002\022Substrait.Protobuf'
  _PLANREL._serialized_start=99
  _PLANREL._serialized_end=187
  _PLAN._serialized_start=190
  _PLAN._serialized_end=506
  _PLANVERSION._serialized_start=508
  _PLANVERSION._serialized_end=558
  _VERSION._serialized_start=560
  _VERSION._serialized_end=671
# @@protoc_insertion_point(module_scope)
