# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: substrait/extensions/extensions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%substrait/extensions/extensions.proto\x12\x14substrait.extensions\x1a\x19google/protobuf/any.proto\"?\n\x12SimpleExtensionURI\x12\x1c\n\x14\x65xtension_uri_anchor\x18\x01 \x01(\r\x12\x0b\n\x03uri\x18\x02 \x01(\t\"\xef\x04\n\x1aSimpleExtensionDeclaration\x12X\n\x0e\x65xtension_type\x18\x01 \x01(\x0b\x32>.substrait.extensions.SimpleExtensionDeclaration.ExtensionTypeH\x00\x12k\n\x18\x65xtension_type_variation\x18\x02 \x01(\x0b\x32G.substrait.extensions.SimpleExtensionDeclaration.ExtensionTypeVariationH\x00\x12`\n\x12\x65xtension_function\x18\x03 \x01(\x0b\x32\x42.substrait.extensions.SimpleExtensionDeclaration.ExtensionFunctionH\x00\x1aS\n\rExtensionType\x12\x1f\n\x17\x65xtension_uri_reference\x18\x01 \x01(\r\x12\x13\n\x0btype_anchor\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x1a\x66\n\x16\x45xtensionTypeVariation\x12\x1f\n\x17\x65xtension_uri_reference\x18\x01 \x01(\r\x12\x1d\n\x15type_variation_anchor\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x1a[\n\x11\x45xtensionFunction\x12\x1f\n\x17\x65xtension_uri_reference\x18\x01 \x01(\r\x12\x17\n\x0f\x66unction_anchor\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\tB\x0e\n\x0cmapping_type\"j\n\x11\x41\x64vancedExtension\x12*\n\x0coptimization\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12)\n\x0b\x65nhancement\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyBb\n\x12io.substrait.protoP\x01Z5github.com/substrait-io/substrait-go/proto/extensions\xaa\x02\x12Substrait.Protobufb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'substrait.extensions.extensions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022io.substrait.protoP\001Z5github.com/substrait-io/substrait-go/proto/extensions\252\002\022Substrait.Protobuf'
  _SIMPLEEXTENSIONURI._serialized_start=90
  _SIMPLEEXTENSIONURI._serialized_end=153
  _SIMPLEEXTENSIONDECLARATION._serialized_start=156
  _SIMPLEEXTENSIONDECLARATION._serialized_end=779
  _SIMPLEEXTENSIONDECLARATION_EXTENSIONTYPE._serialized_start=483
  _SIMPLEEXTENSIONDECLARATION_EXTENSIONTYPE._serialized_end=566
  _SIMPLEEXTENSIONDECLARATION_EXTENSIONTYPEVARIATION._serialized_start=568
  _SIMPLEEXTENSIONDECLARATION_EXTENSIONTYPEVARIATION._serialized_end=670
  _SIMPLEEXTENSIONDECLARATION_EXTENSIONFUNCTION._serialized_start=672
  _SIMPLEEXTENSIONDECLARATION_EXTENSIONFUNCTION._serialized_end=763
  _ADVANCEDEXTENSION._serialized_start=781
  _ADVANCEDEXTENSION._serialized_end=887
# @@protoc_insertion_point(module_scope)
